/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientegrueso;

import javax.swing.JOptionPane;
import ws.Chat;
import ws.Chat_Service;

/**
 *
 * @author sebastian
 */
public class ChatWindow extends javax.swing.JPanel {

    Chat_Service chat = new Chat_Service();
    Chat c = chat.getChatPort();
    HiloRefreshOnlineUsers hiloOU = new HiloRefreshOnlineUsers();
    HiloRefreshMensajes hiloM = new HiloRefreshMensajes(); 
    
    public ChatWindow() {
        ClienteGrueso.chatGrueso.setTitle("Cliente Grueso - " + ClienteGrueso.usuariosOnline + " - " + ClienteGrueso.sala);
        initComponents();
        lConectado.setText("estas conectado como: " + ClienteGrueso.nombreUsuario + " en la sala: " + ClienteGrueso.sala);
        hiloOU.start();
        hiloM.start();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bEnviar = new javax.swing.JButton();
        tEnviar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOnlines = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTextos = new javax.swing.JTextArea();
        lConectado = new javax.swing.JLabel();

        bEnviar.setText("Enviar");
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });

        tOnlines.setColumns(20);
        tOnlines.setEditable(false);
        tOnlines.setRows(5);
        jScrollPane1.setViewportView(tOnlines);

        tTextos.setColumns(20);
        tTextos.setEditable(false);
        tTextos.setRows(5);
        jScrollPane2.setViewportView(tTextos);

        lConectado.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tEnviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEnviar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lConectado)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lConectado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEnviar)
                    .addComponent(tEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        
        //Si en la casilla de enviar mensaje se tiene texto, este se envia si no no
        if(!tEnviar.equals("")){
            
            String enviar = ClienteGrueso.nombreUsuario + " dice: " + tEnviar.getText();
            if(c.newMsg(enviar, ClienteGrueso.sala)){
                tEnviar.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Tu mensaje no se pudo enviar", "Mensaje no se puedo enviar", 0);
            }
            
        }
    }//GEN-LAST:event_bEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lConectado;
    private javax.swing.JTextField tEnviar;
    public static javax.swing.JTextArea tOnlines;
    public static javax.swing.JTextArea tTextos;
    // End of variables declaration//GEN-END:variables
}
