/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientegrueso;

import javax.swing.JOptionPane;
import ws.Chat;
import ws.Chat_Service;

/**
 *
 * @author sebastian
 */
public class Salas extends javax.swing.JPanel {

    Chat_Service chat = new Chat_Service();
    Chat c = chat.getChatPort();
    
    public Salas() {
        ClienteGrueso.chatGrueso.setTitle("Cliente Grueso - " + ClienteGrueso.usuariosOnline );
        initComponents();
        String salas = "";
        for(int i = 0; i < c.getSalas().size(); i++){
            salas += c.getSalas().get(i).toString() + ", ";
        }
        tSalas.setText(salas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bEntrar = new javax.swing.JButton();
        tSalas = new javax.swing.JTextField();

        jLabel1.setText("Salas");

        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });

        tSalas.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tSalas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(bEntrar)
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bEntrar)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
       
        //Si la sala existe se procede a la pantalla de chateo, si no existe se muestra un error
        if(c.checkSala(tSalas.getText())){
            ClienteGrueso.sala = tSalas.getText();
            ChatWindow cw = new ChatWindow();
            ClienteGrueso.chatGrueso.add(cw);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Esta sala no existe, debes de copiarla bien", "Sala no existe", 0);
        }
            
    }//GEN-LAST:event_bEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tSalas;
    // End of variables declaration//GEN-END:variables
}
