/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientegrueso;

import javax.swing.JOptionPane;
import ws.*;

/**
 *
 * @author sebastian
 */
public class Usuario extends javax.swing.JPanel {

    Chat_Service chat = new Chat_Service();
    ws.Chat c = chat.getChatPort();

    
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bEntrar = new javax.swing.JButton();
        tUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(bEntrar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(bEntrar)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        if(tUser.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debes de entrar un nombre de usuario valido", "Nombre de usuario invalido", 0);
        }else{
            if(c.setUserOnline(tUser.getText())){
                Salas salas = new Salas();
                Help help = new Help();
                ClienteGrueso.nombreUsuario = help.capitalize(tUser.getText());
                ClienteGrueso.chatGrueso.add(salas);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "Este usuario ya existe, debes de entrar con un nombre diferente", "Nombre de usuario ya existe", 0);
            }
        }
    }//GEN-LAST:event_bEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
