/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chateo.java
 *
 * Created on 05-may-2012, 8:32:43
 */
package chatgrueso;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastian
 */
public class Chateo extends javax.swing.JPanel {

    /** Creates new form Chateo */
    public Chateo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bEnviar = new javax.swing.JButton();
        tEnviar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        bEnviar.setText("Enviar");
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEnviar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEnviar)
                    .addComponent(tEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        
        Date d = new Date();
        d.setHours(d.getHours()+5);
        String fecha = new Timestamp(d.getTime()).toString();
        String mensaje = tEnviar.getText();
        
        try{
            if(mensaje.equals("")){
                JOptionPane.showMessageDialog(this, "Desde de ingresar un texto para enviar", "Error", WIDTH);
                throw new Exception("Debes de poner un mensaje");
            }
            Connection con = JDBCConnection.getConexion();
            Statement sentencia = con.createStatement();
         
            sentencia.executeUpdate("INSERT INTO mensajes VALUES (NULL , '"+ChatGrueso.nombreUsuario+"', '"+mensaje+"', '"+fecha+"', '"+fecha+"')");
            sentencia.close();
         
            String mensajes = "";
            sentencia = con.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM mensajes ORDER BY created_at LIMIT 0 , 20");
            while (rs.next()){
                mensajes += rs.getString("de") + ": ";
                mensajes += rs.getString("texto") + "\n";
            }
            rs.close();
         
         
            jTextArea1.setText(mensajes);
            tEnviar.setText("");
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }finally{
        }
    }//GEN-LAST:event_bEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tEnviar;
    // End of variables declaration//GEN-END:variables
}
